List<Map<String, dynamic>> Articles = [
  {
    "id": 1,
    "title":
        "'V.I.P Immunization' for the Powerful and Their CroniesRattles South America",
    "subtitle": "Subtitle 1",
    "body": "Body 1",
    "author": "Ram Khatri",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 1",
    "views": 100,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 2,
    "title": "Flutter Class has been finished in Soch College of IT",
    "subtitle": "Subtitle 2",
    "body": "Body 2",
    "author": "Shyam KC",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 2",
    "views": 200,
    "imageUrl": "https://source.unsplash.com/random/800x600?random=1",
    "createdAt": "${DateTime.now().subtract(const Duration(minutes: 35))}"
  },
  {
    "id": 3,
    "title": "LuckDown Season 3 is starting in China",
    "subtitle": "Subtitle 3",
    "body": "Body 3",
    "author": "Hari Bhandari",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 3",
    "views": 300,
    "imageUrl": "https://source.unsplash.com/random/800x600?random=2",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 1))}"
  },
  {
    "id": 4,
    "title": "Candidate Biden Called Saudi Arabia a 'Pariah'",
    "subtitle": "Subtitle 4",
    "body": "Body 4",
    "author": "Geeta Sapkota",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 4",
    "views": 400,
    "imageUrl": "https://source.unsplash.com/random/800x600?random=3",
    "createdAt": "${DateTime.now().subtract(const Duration(minutes: 10))}"
  },
  {
    "id": 5,
    "title": "Title 5",
    "subtitle": "Subtitle 5",
    "body": "Body 5",
    "author": "Author 5",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 5",
    "views": 500,
    "imageUrl": "https://source.unsplash.com/random/800x600?random=4",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 6,
    "title": "Title 6",
    "subtitle": "Subtitle 6",
    "body": "Body 6",
    "author": "Author 6",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 6",
    "views": 600,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 7,
    "title": "Title 7",
    "subtitle": "Subtitle 7",
    "body": "Body 7",
    "author": "Author 7",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 7",
    "views": 700,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 8,
    "title": "Title 8",
    "subtitle": "Subtitle 8",
    "body": "Body 8",
    "author": "Author 8",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 8",
    "views": 800,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 9,
    "title": "Title 9",
    "subtitle": "Subtitle 9",
    "body": "Body 9",
    "author": "Author 9",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 9",
    "views": 900,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 10,
    "title": "Title 10",
    "subtitle": "Subtitle 10",
    "body": "Body 10",
    "author": "Author 10",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 10",
    "views": 1000,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 11,
    "title": "Title 11",
    "subtitle": "Subtitle 11",
    "body": "Body 11",
    "author": "Author 11",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 11",
    "views": 1100,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 12,
    "title": "Title 12",
    "subtitle": "Subtitle 12",
    "body": "Body 12",
    "author": "Author 12",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 12",
    "views": 1200,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 13,
    "title": "Title 13",
    "subtitle": "Subtitle 13",
    "body": "Body 13",
    "author": "Author 13",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 13",
    "views": 1300,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 14,
    "title": "Title 14",
    "subtitle": "Subtitle 14",
    "body": "Body 14",
    "author": "Author 14",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 14",
    "views": 1400,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 15,
    "title": "Title 15",
    "subtitle": "Subtitle 15",
    "body": "Body 15",
    "author": "Author 15",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 15",
    "views": 1500,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 16,
    "title": "Title 16",
    "subtitle": "Subtitle 16",
    "body": "Body 16",
    "author": "Author 16",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 16",
    "views": 1600,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 17,
    "title": "Title 17",
    "subtitle": "Subtitle 17",
    "body": "Body 17",
    "author": "Author 17",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 17",
    "views": 1700,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 18,
    "title": "Title 18",
    "subtitle": "Subtitle 18",
    "body": "Body 18",
    "author": "Author 18",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 18",
    "views": 1800,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 19,
    "title": "Title 19",
    "subtitle": "Subtitle 19",
    "body": "Body 19",
    "author": "Author 19",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 19",
    "views": 1900,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  },
  {
    "id": 20,
    "title": "Title 20",
    "subtitle": "Subtitle 20",
    "body": "Body 20",
    "author": "Author 20",
    "authorImageUrl": "https://source.unsplash.com/random/100x100",
    "category": "Category 20",
    "views": 2000,
    "imageUrl": "https://source.unsplash.com/random/800x600",
    "createdAt": "${DateTime.now().subtract(const Duration(hours: 5))}"
  }
];
